---
- name: Invokes Pig Latin translator CLI
  hosts: all
  vars: 
    message: Hello Pig Latin World
  
  tasks:
  - name: Translate
    ansible.builtin.shell: perl /home/azureuser/piglatin.pl {{ message }}
...
