---
- name: Invokes Pig Latin translator CLI
  hosts: all
  vars: 
    message: Hello Pig Latin World
  
  tasks:
  - name: Translate message
    ansible.builtin.shell: perl /home/azureuser/cli/piglatin.pl "{{ message }}"
    register: response

  - name: Print translated message
    ansible.builtin.debug:
      var: response.stdout
